CREATE TABLE IF NOT EXISTS job(
  id INTEGER NOT NULL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  uid VARCHAR(255) UNIQUE NOT NULL,
  end_date DATE,
  posted_date DATE,
  created_on DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS student(
  id INTEGER NOT NULL PRIMARY KEY,
  chat_id VARCHAR(255) UNIQUE NOT NULL,
  username VARCHAR(255) UNIQUE NOT NULL,
  full_name VARCHAR(255),
  first_name VARCHAR(255),
  notify BOOLEAN DEFAULT FALSE,
  created_on DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS job_status(
  id INTEGER NOT NULL PRIMARY KEY,
  student_id INTEGER NOT NULL,
  job_id INTEGER NOT NULL,
  interested BOOLEAN DEFAULT FALSE,
  applied BOOLEAN DEFAULT FALSE,
  skip BOOLEAN DEFAULT FALSE,
  applied_on DATETIME,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(student_id) REFERENCES student(id),
  FOREIGN KEY(job_id) REFERENCES job(id)
);
